before_script:
  - gem update --system
  - gem install bundler -v '~>1.13'
  - bundler --version
  - make

stages:
  - test
  - release

test_dev:
  image: ruby:1.9
  stage: test
  environment: test
  only:
    - master
  script:
    - ./bin/test.sh

test_19:
  image: ruby:1.9
  stage: test
  environment: test
  only:
    - tags
  script:
    - ./bin/test.sh

test_20:
  image: ruby:2.0
  stage: test
  environment: test
  only:
    - tags
  script:
    - ./bin/test.sh

test_21:
  image: ruby:2.1
  stage: test
  environment: test
  only:
    - tags
  script:
    - ./bin/test.sh

test_22:
  image: ruby:2.2
  stage: test
  environment: test
  only:
    - tags
  script:
    - ./bin/test.sh

test_23:
  image: ruby:2.3
  stage: test
  environment: test
  only:
    - tags
  script:
    - ./bin/test.sh

release:
  image: ruby:2.3
  stage: release
  environment: gem
  only:
    - tags
  script:
    - mkdir -p ~/.gem
    - 'printf "%s\n:rubygems_api_key: %s" "---" "${RUBYGEMSORG_API_KEY}" > ~/.gem/credentials'
    - chmod 0600 ~/.gem/credentials
    - ./bin/release.sh
