language: ruby
rvm:
    - 1.9
    - 2.0
    - 2.1
    - 2.2
    - 2.3
    - ruby-head
sudo: required
before_install:
    - gem update --system
    - gem install bundler -v '~>1.11'
    - bundler --version
install:
    - make
    - gem build thefox-pastebin.gemspec
    - gem install thefox-pastebin-*.gem
    - gem list -l thefox-pastebin
script:
    - make test
    - cd
    - which -a pastebin
    - pastebin --version
